### ISSUE TITLE
Accelerate updating speed and native GCC

### ISSUE THREAD

**Issue by cmjang** [SweetIceLolly/DragControlsIDE-v2#18]
DragControls IDE-v2 is a great c++ IDE, but the update speed is slowing down and the GCC directory needs to be specified manually, which is a bit difficult for a novice. It is hoped that DragControls IDE-v2 will add more practical functions and become an IDE comparable to visual studio in the later stage.

**Comment by SweetIceLolly** [comment]
I will try my best.
