### ISSUE TITLE
ActiveX OCX Not Found !!!

### ISSUE THREAD

**Issue by buger404** [SweetIceLolly/DragControlsIDE-v2#7]
Plz push them next time ........ completely ..... 3q sir !

**Comment by SweetIceLolly** [comment]
> Plz push them next time ........ completely ..... 3q sir !

Already added OCX files.

**Comment by buger404** [comment]
And …… 代码高亮控件什么的。 虽然QQ上发给我了，但是传上来其他开发者才可以正常阅读你的代码
